-- +goose Up

-- Attachments belong to Media, and are the one place the server deliberately opens a
-- payload (ADR-0001). What is stored here is metadata and object keys — never bytes.
-- The bytes go straight from the client to the object store and are read back only by
-- the worker producing variants.
CREATE TABLE attachments (
    id              uuid        PRIMARY KEY,

    -- The conversation this attachment is for, declared when the upload is requested
    -- rather than derived from the entry that later references it. It is what
    -- authorises the upload at all — without it, any account could obtain a signed URL
    -- and write to the bucket — and what tells the worker whom to notify when the
    -- attachment becomes ready.
    conversation_id uuid        NOT NULL,
    owner_id        uuid        NOT NULL,

    -- Declared by the uploader and made binding by the signed URL: the store refuses a
    -- transfer whose length or type differs from what was signed, so these are not
    -- claims that need re-checking on every read.
    content_type    text        NOT NULL,
    byte_size       bigint      NOT NULL,

    -- pending -> uploaded -> ready, or failed. Not an enum type: a state machine that
    -- gains a state should not need a migration that rewrites a type, and the
    -- aggregate is what enforces which transitions are legal.
    state           text        NOT NULL,

    object_key      text        NOT NULL,

    -- Why processing failed, empty otherwise. Kept rather than logged and dropped: a
    -- client showing "this photo could not be processed" needs the state, and whoever
    -- is paged needs the reason attached to the row rather than in a log search.
    failure         text        NOT NULL DEFAULT '',

    created_at      timestamptz NOT NULL,
    ready_at        timestamptz
);

-- Everything a client asks for, it asks for by conversation.
CREATE INDEX attachments_by_conversation ON attachments (conversation_id, created_at DESC);

-- Variants are derived and disposable: the original is retained (MD-5), so any variant
-- can be regenerated by replaying the upload event.
--
-- The primary key is the whole of MD-2. Processing the same attachment twice writes the
-- same two rows twice, and an upsert on this key makes the second pass a no-op rather
-- than a duplicate set — idempotency by constraint, not by the worker remembering what
-- it has done.
CREATE TABLE attachment_variants (
    attachment_id uuid   NOT NULL REFERENCES attachments (id) ON DELETE CASCADE,
    name          text   NOT NULL,
    content_type  text   NOT NULL,
    object_key    text   NOT NULL,
    width         int    NOT NULL,
    height        int    NOT NULL,
    byte_size     bigint NOT NULL,

    PRIMARY KEY (attachment_id, name)
);

-- An entry may carry one attachment. One rather than many because a message with three
-- photos is three messages — which is what clients show anyway, and it keeps the log
-- entry a single indivisible thing.
--
-- Nullable, and deliberately not a foreign key to attachments: Messaging must not
-- depend on Media's schema, and the reference is by ID across a context boundary
-- exactly as the context map says. An attachment that never arrives leaves an entry
-- whose text still reads.
ALTER TABLE entries ADD COLUMN attachment_id uuid;

-- Answering "which position references this attachment", which is how Media asks
-- Messaging whether a viewer is entitled to see it. Partial: almost no entry has one.
CREATE INDEX entries_by_attachment
    ON entries (attachment_id)
    WHERE attachment_id IS NOT NULL;

-- +goose Down

DROP INDEX entries_by_attachment;
ALTER TABLE entries DROP COLUMN attachment_id;
DROP TABLE attachment_variants;
DROP TABLE attachments;
